language: scala
sudo: required
dist: trusty

jdk:
  - openjdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.2.6/0.2.6 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill all {core,runtime}.test

cache:
  directories:
    - $HOME/.coursier
