language: scala
dist: xenial

env:
  global:
    - JAVA_OPTS: -Xss4m

jobs:
  include:
    - stage: formatting
      if: type = pull_request
      script:
        - ./millw __.reformat
        - git diff --exit-code --name-status
        - if [[ $(git diff --exit-code --name-status) ]]; then echo 'Your code is not formatted correctly, please format it, check it and push formatted code'; exit 1; fi
    - stage: test
      script:
        - ./millw runtime.compile
        - ./millw all core.test runtime.test
    - script:
        - ./millw runtime.compile
        - ./millw examples.mdoc

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download

jdk:
  - openjdk11

branches:
  only:
  - master

before_deploy:
  - gem install nanoc kramdown-parser-gfm rouge

deploy:
  - provider: script
    script: bash site/publish_github_pages.sh
    edge: true
    on:
      branch: master
      tags: true
