language: scala
dist: xenial

env:
  global:
    - JAVA_OPTS: -Xss4m

jobs:
  include:
    - stage: formatting
      if: type = pull_request
      script:
        - ./millw __.checkFormat
    - stage: test
      script:
        - ./millw runtime.compile
        - ./millw all core.test runtime.test
    - script:
        - ./millw runtime.compile
        - ./millw examples.mdoc

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download

jdk:
  - openjdk11

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+(-.*)?$/
