name: Assembly jar project
on:
  push:
    branches:
      - feature/swam-server
      - master


jobs:
  build:
    name: Assembly jar project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout latest version of the repo

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: java -version
      - name: Assembly
        run: |
          bash ./millw cli.assembly

      - name: Compress binaries
        run: |
          zip -r cli-0.6.0-RC3.zip out/cli/assembly

      - name: Submit release aligners
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: v0.6.0-RC3
          overwrite: true
          file_glob: true


